<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\ScrcpyNet.Sample.ViewModels\ScrcpyNet.Sample.ViewModels.csproj" />
		<ProjectReference Include="..\ScrcpyNet.Wpf\ScrcpyNet.Wpf.csproj" />
		<ProjectReference Include="..\ScrcpyNet\ScrcpyNet.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="ReactiveUI.WPF.Reactive" Version="25.1.1" />
		<PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
		<PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
	</ItemGroup>

</Project>
